### ISSUE TITLE
The factory example is noct working

### ISSUE THREAD

**Issue by wecapp** [Xinyuan-LilyGO/T-Display-S3#37]
The factory example doesn't work. Is there a correct version?

**Comment by bratoff** [comment]
It worked for me.  Did you follow all the instructions exactly?  What error message are you getting?

**Comment by LilyGO** [comment]
Be careful not to upgrade the TFT library we provide when using the Arduino IDE

**Comment by oldbug62** [comment]
I have the same isue, the display just blinkin what can i do?

**Comment by wecapp** [comment]
I found that a word in factory.cpp appears to be misspelled. Instead of subscribe, the skecht says subsribe. Isn't that a mistake?

**Comment by LilyGO** [comment]
The factory example will use all the libraries in lib, please drag and drop to the C:\Users\NAME\Documents\Arduino\libraries directory

**Comment by bratoff** [comment]
A better place to put the libraries would be C:\Users\NAME\AppData\Local\Arduino15\packages\esp32\hardware\esp32\VERSION\libraries
That way they won't interfere with the Arduino-specific libraries or any other cores you have installed.

**Comment by nfcrugby** [comment]
P.s. Am using Ubuntu 22.04.

**Comment by Vn-ChemGio** [comment]
I has the same issue in Windows 10 and Arduino IDE 2.0.2 when flash file factory.ino

**Comment by Vn-ChemGio** [comment]
> The factory example doesn't work. Is there a correct version?

I've see the reason
root cause by we didn't complete the setup

In my case, I forgot complete step : **Select the settings as shown.** in document
![Arduino_Config](https://user-images.githubusercontent.com/25608423/201821178-163e0967-01db-4350-b5a4-74e2967450cb.png)
--
Note: You can also change timezone, wifi SSID and password in pin_config.h to use your wifi

**Comment by nfcrugby** [comment]
Hi Windblade
I had most of these selected.
Can you just confirm "Core Debug Level:" in English.
I also have Programmer selected as Esptool under Tools and cannot turn that selection off for some reason! 
Any help there would be apreciated

Can I ask you exactly which Factory Version sketch you used? Copy of the link on GitHub would be best.
Thanks

**Comment by Vn-ChemGio** [comment]
Core Debug Level

> Hi Windblade I had most of these selected. Can you just confirm "Core Debug Level:" in English. I also have Programmer selected as Esptool under Tools and cannot turn that selection off for some reason! Any help there would be apreciated
> 
> Can I ask you exactly which Factory Version sketch you used? Copy of the link on GitHub would be best. Thanks

Core Debug Level can be choise is None
Make sure you choose exactly Flash Size, Flash Mode in image above
--
The code in master brand on this repository

---
You can ping me in Telegram and give me your teamview ID for check

**Comment by nfcrugby** [comment]
Hi Again,
Thanks for this advice Vn-ChemGio which I have implemented.

After downloading the complete repo and renaming the folder to remove the dashes (---) I unzipped and manually put everything into the Arduino Library folder. Then I loaded the factory code onto Arduino IDE. BUT --  when I tried to compile I got the error message:
OneButton.h: no such file or directory.

I checked and it is there as are other header files.
I then read somewhere that the header files have to be moved out of the Library folder but my attempts at this have so far failed.  It is not easy for me, a relative newbie. Can anybody give me more precise instructions or tell me where to look?

(I did not include the full error message which is about 10 pages long and beyond my understanding.)
Again, for info, I am working on Ubuntu 22.04.

Many Thanks for your patience.

**Comment by Vn-ChemGio** [comment]
Make sure you have installed all library bellow before compiler 
- ArduinoTEA5767
- OneButton
- Time
- Timezone
- TouchLib

**Comment by csylvain** [comment]
i discovered that 
1. after copying all the directories in 'lib' in this repo to ~/Arduino/libraries, then
2. move all files from TouchLib/src to TouchLib, 
3. and remove 'src' from TouchLib. 

Verify/Compile will then work without generating any error messages.

**Comment by linjian128** [comment]
@csylvain     Hi,   I still cannot  succeed to compile  "lv_demos", seems the "demo" folder is not included in the compile path. 
Did you have some other configuration after the readme?

**Comment by mmMicky** [comment]
You can try to use platformIO to compile. I have specified the library directory and demo compilation path on this tool. Just open the example independently and click upload.

**Comment by mmMicky** [comment]
Problem seems to be resolved. I will close this issue
